# This is a basic workflow that is aotomatically triggered

name: Automatic workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: "*/4 * * * *"
  
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

        with:
          repository: .github/.github
          
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: .github/.github/workflows/manual.yml
      - name: Run my action
       # uses: ./.github/actions/my-private-repo/my-action
      
      
      
      
      
