# This is a basic workflow that is aotomatically triggered

name: Automatic workflow


on:
  workflow_dispatch:
  schedule:
    - cron: "*/4 * * * *"
  
    
jobs:
  # This workflow contains a single job called "UI_test"
  UI_test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        path: newrepo/tests
      
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        robot project.robot
      
    - run: |
        echo "Hellooooo Shivam"
      #  path: newrepo/tests/project.robot
      
      
      
      
      
